### ISSUE TITLE
IPFS does not take into account the psychology of hording

### ISSUE THREAD

**Issue by Bazmundi** [ipfs/papers#20]
I rather think the failure mode of IPFS is not technological.  You need to understand the motivations for people to horde copies of files.  There is a base instinctual gluttony going on.  Note the problems newspapers had going on line, complaining that after an hour one line a story would be copied upwards of 70,000 times!  Why?  Event though billions of internet "nodes" need only surf to that one URL, it was copied, why? Understand the why.  Somehow people feel empowered by "owning" the information, somehow "possessing" it.  It  rather seems not unlike the apocryphal stories around cannibals where they would welcome you up to the point when they know your name - then they eat you.  Power is in information ownership.  Much is likely hinging on the idea of "presentation" of information has more status than generation of intellectual property - as questions of "authorship" become muddled on the web.  It is now more important to "present" in the "guise" of authorship.  Or at least that is my humble opinion.  Great idea though, if only it came first ... before the URL and before the Web.  You might also want to read into Single Source documentation approaches, to see how they are faring as they are attempting for or less an analogue of what you are trying to do with the internet, at least locally with "books" and "manuals".

**Comment by hsanjuan** [comment]
This is not papers-related. Suggest you try to discuss it in https://discuss.ipfs.io
