### ISSUE TITLE
ipfs-p2p-file-system.pdf DNS TXT IPNS Records, is the keyname ipfs or ipns?

### ISSUE THREAD

**Issue by bostikforever** [ipfs/papers#3]
The DNS TXT records paragraph under Section 3.7.2 (Human friendly names) says the key is `ipns`, however the example shows the key as `ipfs`

**Comment by jbenet** [comment]
@bostikforever sorry, paper is outdated-- the key is now `dnslink` as in any of these:

```
dnslink=/ipfs/QmXX7YRpU7nNBKfw75VG7Y1c3GwpSAGHRev67XVPgZFv9R
dnslink=/ipns/QmbBHw1Xx9pUpAbrVZUKTPL5Rsph5Q9GQhRvcWVBPFgGtC
```

**Comment by bostikforever** [comment]
Any plans to update it? There were a few other typos that, but they didn't otherwise affect understanding.

**Comment by jbenet** [comment]
yes i hope to write DRAFT 4 before end of summer.

**Comment by bostikforever** [comment]
Great! Looking forward! :+1:
