### ISSUE TITLE
define merkle dag

### ISSUE THREAD

**Issue by dominictarr** [ipfs/papers#4]
You mention the phrase "Merkle DAG" several times, as if this is a common term, the closest you get to defining it is in footnote 2.

From what I can tell, it @jbenet just invented this term? (not the idea, but the term--a search for "Merkle DAG" results mostly in ipfs pages!)

You should not assume that the reader has already had the Content Addressability/Merkle DAG/Hash Links Revelation... Instead, you should explain the properties, why you have called it a Merkle DAG, or cite a paper that does.

**Comment by jbenet** [comment]
yep, plan is to eventually write a paper about merkle dags and why they're valuable. 

> From what I can tell, it @jbenet just invented this term? (not the idea, but the term--a search for "Merkle DAG" results mostly in ipfs pages!)

See why here https://github.com/jbenet/random-ideas/issues/20#issue-36190824 -- also, merkle_web_, but that's only in the web-context.

**Comment by tapaswenipathak** [comment]
Hi @jbenet, is the ticket open? Can I work on the ticket or is this internal?

**Comment by Stebalien** [comment]
If you'd like to fix this, adding a link to https://en.wikipedia.org/wiki/Merkle_tree and https://en.wikipedia.org/wiki/Directed_acyclic_graph to that footnote is probably enough for now (I'd be happy to review a PR if you tag me).

More generally, the implementation and paper have diverged enough that fixing small issues in the paper may not be worth it.

**Comment by tapaswenipathak** [comment]
Done, attached.
