### ISSUE TITLE
[meta] paper pdf not openable, says pdf is corrupt

### ISSUE THREAD

**Issue by NotAFile** [ipfs/papers#7]
when attempting to open the main paper, all of the PDF readers available to me claim the PDF is invalid or corrupt

**Comment by jbenet** [comment]
odd, works for me just fine. OS/platform?

try https://ipfs.io/ipfs/QmR7GSQM93Cx5eAg6a6yRzNde1FQv7uL6X1o4k7zrJa3LX/ipfs.draft3.pdf

**Comment by NotAFile** [comment]
Works fine for me on desktop now, but on my Android phone all of the following readers claim it is invalid:
- Kindle
- Google Docs
- Adobe Reader
- A couple of E-Book readers
